"""Create mood_entries table

Revision ID: 38843b598663
Revises: c351ea66db9f
Create Date: 2026-07-11 02:37:01.532262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38843b598663'
down_revision = 'c351ea66db9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mood_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mood', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mood_entries')
    # ### end Alembic commands ###
